@http=https://localhost:7002

GET {{http}}/auth/login
Content-Type: application/json

{
  "Email":"my email",
  "Password":"my passwrod"
}
###

GET {{http}}/auth/logon
Content-Type: application/json

{
  "FirstName":"My First Name",
  "LastName":"My Last Name",
  "Email":"my email",
  "Password":"my passwrod"
}